# Generated by Django 4.2.17 on 2025-01-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0002_profile_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="preferences",
            field=models.TextField(blank=True, null=True),
        ),
    ]
