# Generated by Django 4.2.18 on 2025-02-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0005_rechargerecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="preferences",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
