# Generated by Django 4.2.17 on 2025-01-29 16:20

import bread_management.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bread_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bread",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=bread_management.models.bread_image_upload_path,
            ),
        ),
    ]
