# Generated by Django 4.2.18 on 2025-02-10 12:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bread_management", "0003_alter_bread_options_alter_category_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="breads",
        ),
    ]
