# Generated by Django 4.2.18 on 2025-02-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bread_management", "0004_remove_category_breads"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="breads",
            field=models.ManyToManyField(
                related_name="categories", to="bread_management.bread"
            ),
        ),
    ]
