# Generated by Django 4.2.18 on 2025-02-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_management", "0002_alter_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_processed",
            field=models.BooleanField(default=False),
        ),
    ]
